import os
print(os.getcwd())
#os.mkdir("New")
os.chdir("New")
print(os.getcwd())
#print(os.getcwd())
#os.chdir("D:\Python")
#os.rmdir("New")
#print(os.getcwd())
#os.mkdir("New")
#os.chdir("New")
#print(os.getcwd())
fo=open("new.txt","w")
fo.write("Hello world")
print(fo.closed)
fo.close()
fo=open("new.txt","r+")
stri=fo.read()
print(stri)

fo=open("new.txt","a+")
fo.write("ello")
a=fo.read()
print(a)
fo.close()
fo=open("new.txt","w")
fo.write("luffy")
fo.close()

fo=open("new.py","w+")
fo.write("""
print("Hello World")
""")
fo.close()
print(os.getcwd())